local orgs = import 'vendor/otterdog-defaults/otterdog-defaults.libsonnet';

local osgiBranchProtectionRule(branchName) = orgs.newBranchProtectionRule(branchName) {
  required_approving_review_count: 1,
  requires_strict_status_checks: true,
};

local newOSGiRepo(repoName, default_branch = 'main') = orgs.newRepo(repoName) {
  allow_update_branch: false,
  default_branch: default_branch,
  delete_branch_on_merge: false,
  dependabot_security_updates_enabled: true,
  has_wiki: false,
  homepage: "https://www.osgi.org",
  branch_protection_rules: [
    osgiBranchProtectionRule($.default_branch) {},
  ],
};


// Spec repos of the Maven multi-repo split: identical settings for all.
// Relaxed for the history import; fields marked "flip after migration" get strict afterwards.
local osgiSpecBranchProtectionRule(branchName) = orgs.newBranchProtectionRule(branchName) {
  required_approving_review_count: 1,
  requires_pull_request: false,        // flip after migration (allows direct push of imported history)
  requires_linear_history: false,      // flip after migration (imported history contains merge commits)
  allows_force_pushes: true,           // flip after migration (allows replacing the bot initial commit)
  requires_strict_status_checks: true,
};

local newOSGiSpecRepo(repoName, description, default_branch = 'main') = orgs.newRepo(repoName) {
  description: description,
  allow_squash_merge: false,
  allow_update_branch: false,
  default_branch: default_branch,
  delete_branch_on_merge: false,
  dependabot_security_updates_enabled: true,
  has_wiki: false,
  homepage: "https://www.osgi.org",
  web_commit_signoff_required: false,
  branch_protection_rules: [
    osgiSpecBranchProtectionRule($.default_branch) {},
  ],
};

// All repos of the Maven multi-repo split.
local specRepoNames = [
  'org.osgi.maven.pom',
  'org.osgi.test.support',
  'org.osgi.annotation.bundle',
  'org.osgi.annotation.versioning',
  'org.osgi.dto',
  'org.osgi.framework',
  'org.osgi.namespace.contract',
  'org.osgi.namespace.extender',
  'org.osgi.namespace.implementation',
  'org.osgi.namespace.service',
  'org.osgi.namespace.unresolvable',
  'org.osgi.resource',
  'org.osgi.service.async',
  'org.osgi.service.cdi',
  'org.osgi.service.clusterinfo',
  'org.osgi.service.cm',
  'org.osgi.service.component',
  'org.osgi.service.component.annotations',
  'org.osgi.service.condition',
  'org.osgi.service.condpermadmin',
  'org.osgi.service.configurator',
  'org.osgi.service.coordinator',
  'org.osgi.service.dal',
  'org.osgi.service.dal.functions',
  'org.osgi.service.device',
  'org.osgi.service.dmt',
  'org.osgi.service.enocean',
  'org.osgi.service.event',
  'org.osgi.service.feature',
  'org.osgi.service.featurelauncher',
  'org.osgi.service.jakartars',
  'org.osgi.service.jdbc',
  'org.osgi.service.jdkhttp',
  'org.osgi.service.jndi',
  'org.osgi.service.jpa',
  'org.osgi.service.log',
  'org.osgi.service.log.stream',
  'org.osgi.service.metatype',
  'org.osgi.service.metatype.annotations',
  'org.osgi.service.networkadapter',
  'org.osgi.service.onem2m',
  'org.osgi.service.packageadmin',
  'org.osgi.service.permissionadmin',
  'org.osgi.service.prefs',
  'org.osgi.service.remoteserviceadmin',
  'org.osgi.service.repository',
  'org.osgi.service.resolver',
  'org.osgi.service.resourcemonitoring',
  'org.osgi.service.rest',
  'org.osgi.service.serial',
  'org.osgi.service.serviceloader',
  'org.osgi.service.servlet',
  'org.osgi.service.startlevel',
  'org.osgi.service.tr069todmt',
  'org.osgi.service.transaction.control',
  'org.osgi.service.typedevent',
  'org.osgi.service.upnp',
  'org.osgi.service.url',
  'org.osgi.service.usbinfo',
  'org.osgi.service.useradmin',
  'org.osgi.service.webservice',
  'org.osgi.service.wireadmin',
  'org.osgi.service.zigbee',
  'org.osgi.service.jta',
  'org.osgi.service.war',
  'org.osgi.util.converter',
  'org.osgi.util.function',
  'org.osgi.util.promise',
  'org.osgi.util.pushstream',
  'org.osgi.util.tracker',
  'org.osgi.util.xml',
];


orgs.newOrg('technology.osgi', 'osgi') {
  settings+: {
    blog: "https://www.osgi.org",
    description: "The Dynamic Module System for Java",
    members_can_fork_private_repositories: true,
    name: "OSGi Working Group",
    security_managers+: [
      "osgi-security-team"
    ],
    twitter_username: "OSGiWG",
    web_commit_signoff_required: false,
    workflows+: {
      actions_can_approve_pull_request_reviews: false,
    },
  },
  teams+: [
    orgs.newTeam('Organization Owners') {
      members+: [
        "bjhargrave",
        "bosschaert",
        "eclipsewebmaster"
      ],
    },
  ],
  secrets+: [
    orgs.newOrgSecret('GPG_KEY_ID') {
      selected_repositories+: [
        "osgi"
      ] + specRepoNames,
      value: "pass:bots/technology.osgi/gpg/key_id",
      visibility: "selected",
    },
    orgs.newOrgSecret('GPG_PASSPHRASE') {
      selected_repositories+: [
        "osgi"
      ] + specRepoNames,
      value: "pass:bots/technology.osgi/gpg/passphrase",
      visibility: "selected",
    },
    orgs.newOrgSecret('GPG_PRIVATE_KEY') {
      selected_repositories+: [
        "osgi"
      ] + specRepoNames,
      value: "pass:bots/technology.osgi/gpg/secret-subkeys.asc",
      visibility: "selected",
    },
    orgs.newOrgSecret('CENTRAL_SONATYPE_TOKEN_PASSWORD') {
      selected_repositories+: [
        "osgi"
      ] + specRepoNames,
      value: "pass:bots/technology.osgi-technology/central.sonatype.org/token-password",
      visibility: "selected",
    },
    orgs.newOrgSecret('CENTRAL_SONATYPE_TOKEN_USERNAME') {
      selected_repositories+: [
        "osgi"
      ] + specRepoNames,
      value: "pass:bots/technology.osgi-technology/central.sonatype.org/token-username",
      visibility: "selected",
    },
  ],
  _repositories+:: [
    orgs.newRepo('.github') {
      allow_merge_commit: true,
      allow_update_branch: false,
      delete_branch_on_merge: false,
      dependabot_alerts_enabled: false,
      description: "Community Health",
      has_issues: false,
      has_projects: false,
      has_wiki: false,
      web_commit_signoff_required: false,
    },
    orgs.newRepo('bindex') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      description: "OSGi Bundle Repository Indexer MOVED to https://github.com/bndtools/bnd/tree/master/org.osgi.impl.bundle.repoindex.cli",
      has_issues: false,
      has_wiki: false,
      homepage: "",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('bugzilla-archive') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      description: "Archive of OSGi Alliance Specification Bugzilla bugs. The Specification Bugzilla system was decommissioned with the move to GitHub. The issues in this repository are imported from the Specification Bugzilla system for archival purposes.",
      has_projects: false,
      has_wiki: false,
      homepage: "",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('bundles') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      description: "REPLACED BY osgi.enroute",
      homepage: "",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('design') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      delete_branch_on_merge: false,
      description: "OSGi design repository",
      has_projects: false,
      homepage: "",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      topics+: [
        "feedback",
        "osgi"
      ],
      web_commit_signoff_required: false,
    },
    orgs.newRepo('docs') {
      allow_merge_commit: true,
      allow_update_branch: false,
      default_branch: "gh-pages",
      dependabot_alerts_enabled: false,
      description: "OSGi Specification Project Documentation Website. Specifications, Javadoc, and more.",
      gh_pages_build_type: "legacy",
      gh_pages_source_branch: "gh-pages",
      gh_pages_source_path: "/",
      has_projects: false,
      has_wiki: false,
      homepage: "https://docs.osgi.org",
      topics+: [
        "downloads",
        "javadoc",
        "osgi",
        "reference",
        "specification",
        "whitepaper"
      ],
      web_commit_signoff_required: false,
      workflows+: {
        allow_action_patterns+: [
          "ruby/setup-ruby@*"
        ],
        allow_verified_creator_actions: false,
        allowed_actions: "selected",
      },
      environments: [
        orgs.newEnvironment('github-pages'),
      ],
    },
    orgs.newRepo('eclipse-ata') {
      allow_merge_commit: true,
      allow_update_branch: false,
      delete_branch_on_merge: false,
      dependabot_alerts_enabled: false,
      description: "OSGi Assets to Transfer",
      private: true,
      web_commit_signoff_required: false,
    },
    orgs.newRepo('eclipsecon') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      description: "Some tutorials from past OSGi DevCons",
      has_issues: false,
      has_wiki: false,
      homepage: "",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('materials') {
      allow_merge_commit: true,
      allow_update_branch: false,
      delete_branch_on_merge: false,
      description: "Published OSGi Materials. All releases of the OSGi specifications and TCKs are stored here for archival purposes.",
      has_projects: false,
      has_wiki: false,
      homepage: "",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('osgi') {
      allow_merge_commit: true,
      allow_update_branch: true,
      dependabot_security_updates_enabled: true,
      description: "OSGi Specification Project Build Repository. Specification, API, implementation, and TCK source code.",
      gh_pages_build_type: "legacy",
      gh_pages_source_branch: "gh-pages",
      gh_pages_source_path: "/",
      has_discussions: true,
      homepage: "https://docs.osgi.org/",
      topics+: [
        "eclipse",
        "osgi",
        "osgi-specification",
        "specification",
        "working-group"
      ],
      web_commit_signoff_required: false,
      workflows+: {
        allow_action_patterns+: [
          "gradle/gradle-build-action@*",
          "gradle/actions/wrapper-validation@*",
          "gradle/wrapper-validation-action@*",
          "gradle/actions/setup-gradle@*",
          "peaceiris/actions-gh-pages@*"
        ],
        allow_verified_creator_actions: false,
        allowed_actions: "selected",
      },
      environments: [
        orgs.newEnvironment('github-pages'),
      ],
    },
    orgs.newRepo('osgi.enroute.blog') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "00-initial",
      delete_branch_on_merge: false,
      description: "A tutorial to demonstrate how to build HTML-5 Applications with OSGi",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('osgi.enroute.bundles') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      description: "REPLACED BY osgi.enroute",
      has_projects: false,
      has_wiki: false,
      homepage: "",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('osgi.enroute.example.knowhowlab.testing') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      description: "In progress ... will be an OSGi enRoute testing example",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('osgi.enroute.examples') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      description: "A repository with small examples showing off OSGi",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
      webhooks: [
        orgs.newRepoWebhook('https://notify.travis-ci.org') {
          events+: [
            "create",
            "delete",
            "issue_comment",
            "member",
            "public",
            "pull_request",
            "push",
            "repository"
          ],
        },
      ],
    },
    orgs.newRepo('osgi.enroute.examples.concurrency') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      description: "Examples for the Concurrency best practices App Note on enRoute http://enroute.osgi.org/appnotes/concurrency.html",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('osgi.enroute.examples.eval') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      description: "A Maven+vi only OSGi enRoute example",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
      webhooks: [
        orgs.newRepoWebhook('https://notify.travis-ci.org') {
          events+: [
            "create",
            "delete",
            "issue_comment",
            "member",
            "public",
            "pull_request",
            "push",
            "repository"
          ],
        },
      ],
    },
    orgs.newRepo('osgi.enroute.examples.jdbc') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      description: "A project used to develop the way OSGi enRoute could use persistence",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('osgi.enroute.examples.ledovermqtt') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('osgi.enroute.examples.maven') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      dependabot_security_updates_enabled: true,
      description: "Provides an example of a setup with the Maven Bnd Repository Plugin.",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('osgi.enroute.examples.polymer') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      description: "An example OSGi enRoute application using Polymer",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('osgi.enroute.examples.vaadin') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('osgi.enroute.template') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      description: "REPLACED BY osgi.enroute",
      has_issues: false,
      has_projects: false,
      has_wiki: false,
      homepage: "",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('osgi.enroute.trains') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('osgi.iot.contest.sdk') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      description: "The OSGi IoT Trains SDK.  A description of the architecture is available at http://enroute.osgi.org/trains/200-architecture.html",
      homepage: "http://enroute.osgi.org/trains/200-architecture.html",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('osgi.security-tests') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      description: "Security Best Practices Tests for OSGi Framework Implementations",
      homepage: "",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('v2archive.osgi.enroute') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      dependabot_security_updates_enabled: true,
      description: "An archive of the OSGi enRoute v2 repo. This enRoute v2 archive repo is kept as a resource for those already using OSGi enRoute v2. If you are new to OSGi enRoute, then please start with the latest OSGi enRoute at https://enroute.osgi.org/. ",
      homepage: "https://v2archive.enroute.osgi.org/",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
      webhooks: [
        orgs.newRepoWebhook('https://notify.travis-ci.org') {
          events+: [
            "create",
            "delete",
            "issue_comment",
            "member",
            "public",
            "pull_request",
            "push",
            "repository"
          ],
        },
      ],
    },
    orgs.newRepo('v2archive.osgi.enroute.site') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "gh-pages",
      delete_branch_on_merge: false,
      dependabot_security_updates_enabled: true,
      description: "An archive of the OSGi enRoute v2 website. This enRoute v2 archive site is kept as a resource for those already using OSGi enRoute v2. If you are new to OSGi enRoute, then please start with the latest OSGi enRoute at  https://enroute.osgi.org/.",
      gh_pages_build_type: "legacy",
      gh_pages_source_branch: "gh-pages",
      gh_pages_source_path: "/",
      homepage: "https://v2archive.enroute.osgi.org/",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
      environments: [
        orgs.newEnvironment('github-pages'),
      ],
    },
    orgs.newRepo('v2archive.osgi.enroute.workspace') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      description: "An archive of the OSGi enRoute v2 workspace. This enRoute v2 archive workspace is kept as a resource for those already using OSGi enRoute v2. If you are new to OSGi enRoute, then please start with the latest OSGi enRoute at https://enroute.osgi.org/. ",
      homepage: "",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('whiteboard-pattern') {
      allow_merge_commit: true,
      allow_update_branch: false,
      default_branch: "master",
      delete_branch_on_merge: false,
      description: "Example code for the OSGi Whiteboard Pattern whitepaper",
      homepage: "https://docs.osgi.org/whitepaper/whiteboard-pattern/",
      web_commit_signoff_required: false,
    },
    orgs.newRepo('workspace') {
      allow_merge_commit: true,
      allow_update_branch: false,
      archived: true,
      default_branch: "master",
      delete_branch_on_merge: false,
      description: "REPLACED BY enroute.workspace",
      homepage: "",
      secret_scanning: "disabled",
      secret_scanning_push_protection: "disabled",
      web_commit_signoff_required: false,
    },

    newOSGiRepo('org.osgi.maven.pom') {
      description: "Maven Parent POM",
    },

    newOSGiSpecRepo('org.osgi.maven.pom', 'Maven Parent POM for all OSGi Specifications'),
    newOSGiSpecRepo('org.osgi.test.support', 'OSGi Test Support bundle'),

    newOSGiSpecRepo('org.osgi.annotation.bundle', 'OSGi Specification repo for org.osgi.annotation.bundle'),
    newOSGiSpecRepo('org.osgi.annotation.versioning', 'OSGi Specification repo for org.osgi.annotation.versioning'),
    newOSGiSpecRepo('org.osgi.dto', 'OSGi Specification repo for org.osgi.dto'),
    newOSGiSpecRepo('org.osgi.framework', 'OSGi Specification repo for org.osgi.framework'),
    newOSGiSpecRepo('org.osgi.namespace.contract', 'OSGi Specification repo for org.osgi.namespace.contract'),
    newOSGiSpecRepo('org.osgi.namespace.extender', 'OSGi Specification repo for org.osgi.namespace.extender'),
    newOSGiSpecRepo('org.osgi.namespace.implementation', 'OSGi Specification repo for org.osgi.namespace.implementation'),
    newOSGiSpecRepo('org.osgi.namespace.service', 'OSGi Specification repo for org.osgi.namespace.service'),
    newOSGiSpecRepo('org.osgi.namespace.unresolvable', 'OSGi Specification repo for org.osgi.namespace.unresolvable'),
    newOSGiSpecRepo('org.osgi.resource', 'OSGi Specification repo for org.osgi.resource'),
    newOSGiSpecRepo('org.osgi.service.async', 'OSGi Specification repo for org.osgi.service.async'),
    newOSGiSpecRepo('org.osgi.service.cdi', 'OSGi Specification repo for org.osgi.service.cdi'),
    newOSGiSpecRepo('org.osgi.service.clusterinfo', 'OSGi Specification repo for org.osgi.service.clusterinfo'),
    newOSGiSpecRepo('org.osgi.service.cm', 'OSGi Specification repo for org.osgi.service.cm'),
    newOSGiSpecRepo('org.osgi.service.component', 'OSGi Specification repo for org.osgi.service.component'),
    newOSGiSpecRepo('org.osgi.service.component.annotations', 'OSGi Specification repo for org.osgi.service.component.annotations'),
    newOSGiSpecRepo('org.osgi.service.condition', 'OSGi Specification repo for org.osgi.service.condition'),
    newOSGiSpecRepo('org.osgi.service.condpermadmin', 'OSGi Specification repo for org.osgi.service.condpermadmin'),
    newOSGiSpecRepo('org.osgi.service.configurator', 'OSGi Specification repo for org.osgi.service.configurator'),
    newOSGiSpecRepo('org.osgi.service.coordinator', 'OSGi Specification repo for org.osgi.service.coordinator'),
    newOSGiSpecRepo('org.osgi.service.dal', 'OSGi Specification repo for org.osgi.service.dal'),
    newOSGiSpecRepo('org.osgi.service.dal.functions', 'OSGi Specification repo for org.osgi.service.dal.functions'),
    newOSGiSpecRepo('org.osgi.service.device', 'OSGi Specification repo for org.osgi.service.device'),
    newOSGiSpecRepo('org.osgi.service.dmt', 'OSGi Specification repo for org.osgi.service.dmt'),
    newOSGiSpecRepo('org.osgi.service.enocean', 'OSGi Specification repo for org.osgi.service.enocean'),
    newOSGiSpecRepo('org.osgi.service.event', 'OSGi Specification repo for org.osgi.service.event'),
    newOSGiSpecRepo('org.osgi.service.feature', 'OSGi Specification repo for org.osgi.service.feature'),
    newOSGiSpecRepo('org.osgi.service.featurelauncher', 'OSGi Specification repo for org.osgi.service.featurelauncher'),
    newOSGiSpecRepo('org.osgi.service.jakartars', 'OSGi Specification repo for org.osgi.service.jakartars'),
    newOSGiSpecRepo('org.osgi.service.jdbc', 'OSGi Specification repo for org.osgi.service.jdbc'),
    newOSGiSpecRepo('org.osgi.service.jdkhttp', 'OSGi Specification repo for org.osgi.service.jdkhttp'),
    newOSGiSpecRepo('org.osgi.service.jndi', 'OSGi Specification repo for org.osgi.service.jndi'),
    newOSGiSpecRepo('org.osgi.service.jpa', 'OSGi Specification repo for org.osgi.service.jpa'),
    newOSGiSpecRepo('org.osgi.service.log', 'OSGi Log Service Specification'),
    newOSGiSpecRepo('org.osgi.service.log.stream', 'OSGi Specification repo for org.osgi.service.log.stream'),
    newOSGiSpecRepo('org.osgi.service.metatype', 'OSGi Specification repo for org.osgi.service.metatype'),
    newOSGiSpecRepo('org.osgi.service.metatype.annotations', 'OSGi Specification repo for org.osgi.service.metatype.annotations'),
    newOSGiSpecRepo('org.osgi.service.networkadapter', 'OSGi Specification repo for org.osgi.service.networkadapter'),
    newOSGiSpecRepo('org.osgi.service.onem2m', 'OSGi Specification repo for org.osgi.service.onem2m'),
    newOSGiSpecRepo('org.osgi.service.packageadmin', 'OSGi Specification repo for org.osgi.service.packageadmin'),
    newOSGiSpecRepo('org.osgi.service.permissionadmin', 'OSGi Specification repo for org.osgi.service.permissionadmin'),
    newOSGiSpecRepo('org.osgi.service.prefs', 'OSGi Specification repo for org.osgi.service.prefs'),
    newOSGiSpecRepo('org.osgi.service.remoteserviceadmin', 'OSGi Specification repo for org.osgi.service.remoteserviceadmin'),
    newOSGiSpecRepo('org.osgi.service.repository', 'OSGi Specification repo for org.osgi.service.repository'),
    newOSGiSpecRepo('org.osgi.service.resolver', 'OSGi Specification repo for org.osgi.service.resolver'),
    newOSGiSpecRepo('org.osgi.service.resourcemonitoring', 'OSGi Specification repo for org.osgi.service.resourcemonitoring'),
    newOSGiSpecRepo('org.osgi.service.rest', 'OSGi Specification repo for org.osgi.service.rest'),
    newOSGiSpecRepo('org.osgi.service.serial', 'OSGi Specification repo for org.osgi.service.serial'),
    newOSGiSpecRepo('org.osgi.service.serviceloader', 'OSGi Specification repo for org.osgi.service.serviceloader'),
    newOSGiSpecRepo('org.osgi.service.servlet', 'OSGi Servlet (Whiteboard) Specification (formerly Http Whiteboard / Http Service)'),
    newOSGiSpecRepo('org.osgi.service.startlevel', 'OSGi Specification repo for org.osgi.service.startlevel'),
    newOSGiSpecRepo('org.osgi.service.tr069todmt', 'OSGi Specification repo for org.osgi.service.tr069todmt'),
    newOSGiSpecRepo('org.osgi.service.transaction.control', 'OSGi Specification repo for org.osgi.service.transaction.control'),
    newOSGiSpecRepo('org.osgi.service.typedevent', 'OSGi Specification repo for org.osgi.service.typedevent'),
    newOSGiSpecRepo('org.osgi.service.upnp', 'OSGi Specification repo for org.osgi.service.upnp'),
    newOSGiSpecRepo('org.osgi.service.url', 'OSGi Specification repo for org.osgi.service.url'),
    newOSGiSpecRepo('org.osgi.service.usbinfo', 'OSGi Specification repo for org.osgi.service.usbinfo'),
    newOSGiSpecRepo('org.osgi.service.useradmin', 'OSGi Specification repo for org.osgi.service.useradmin'),
    newOSGiSpecRepo('org.osgi.service.webservice', 'OSGi Specification repo for org.osgi.service.webservice'),
    newOSGiSpecRepo('org.osgi.service.wireadmin', 'OSGi Specification repo for org.osgi.service.wireadmin'),
    newOSGiSpecRepo('org.osgi.service.zigbee', 'OSGi Specification repo for org.osgi.service.zigbee'),
    newOSGiSpecRepo('org.osgi.service.jta', 'OSGi Specification repo for Transaction Service Specification'),
    newOSGiSpecRepo('org.osgi.service.war', 'OSGi Specification repo for Web Applications Specification'),
    newOSGiSpecRepo('org.osgi.util.converter', 'OSGi Specification repo for org.osgi.util.converter'),
    newOSGiSpecRepo('org.osgi.util.function', 'OSGi Specification repo for org.osgi.util.function'),
    newOSGiSpecRepo('org.osgi.util.promise', 'OSGi Specification repo for org.osgi.util.promise'),
    newOSGiSpecRepo('org.osgi.util.pushstream', 'OSGi Specification repo for org.osgi.util.pushstream'),
    newOSGiSpecRepo('org.osgi.util.tracker', 'OSGi Specification repo for org.osgi.util.tracker'),
    newOSGiSpecRepo('org.osgi.util.xml', 'OSGi Specification repo for org.osgi.util.xml'),
    newOSGiSpecRepo('org.osgi.test.support', 'OSGi Test Support repo org.osgi.test.support'),

  ],
}
